Revert "Fix cpufreq_cooling build."
Fix error below.

kernel/sched/MuQSS.c:3408:6: error: conflicting types for ‘arch_set_thermal_pressure’
 3408 | void arch_set_thermal_pressure(struct cpumask *cpus,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/energy_model.h:10,
                 from ./include/linux/device.h:16,
                 from ./include/linux/node.h:18,
                 from ./include/linux/cpu.h:17,
                 from ./include/linux/perf_event.h:50,
                 from ./include/linux/trace_events.h:10,
                 from ./include/trace/trace_events.h:21,
                 from ./include/trace/define_trace.h:102,
                 from ./include/trace/events/sched.h:652,
                 from kernel/sched/MuQSS.c:35:
./include/linux/sched/topology.h:247:6: note: previous definition of ‘arch_set_thermal_pressure’ was here
  247 | void arch_set_thermal_pressure(const struct cpumask *cpus,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~

This reverts commit 89377b9c04f525cb07b1bc7ce48f1fe226a5c45b.