Revert "mm: support POSIX_FADV_NOREUSE"
Build is broken:

    In file included from drivers/block/drbd/drbd_worker.c:20:
    ./include/linux/mm_inline.h: In function ‘lru_gen_del_folio’:
    ./include/linux/mm_inline.h:285:13: error: ‘vma’ undeclared (first use in this function); did you mean ‘cma’?
    285 |         if (vma->vm_file && (vma->vm_file->f_mode & FMODE_NOREUSE))
    |             ^~~
    |             cma
    ./include/linux/mm_inline.h:285:13: note: each undeclared identifier is reported only once for each function it appears in

This reverts commit d6c71ea1757a88f92cc0880ee6c882e4b4940a5c.