Revert "spi: cs42l43: Use actual ACPI firmware node for chip selects"
Fails to compile with v6.18.2.

    drivers/spi/spi-cs42l43.c:376:49: error: initialization of
    ‘const struct software_node *’ from incompatible pointer type
    ‘struct fwnode_handle *’ [-Wincompatible-pointer-types]

This reverts commit ff23044abec9cc2363c2b37ab394fd1a9f11ed00.