Revert "perf bench: Add futex2 benchmark tests"
With this commit, we get the following output when we try to build perf.

In file included from bench/futex-hash.c:29:
bench/futex.h:129:50: error: ‘struct futex_requeue’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
  129 | static inline int futex2_requeue(volatile struct futex_requeue *uaddr1,
      |                                                  ^~~~~~~~~~~~~
bench/futex-hash.c: In function ‘__bench_futex_hash’:
bench/futex-hash.c:156:16: error: ‘FUTEX_32’ undeclared (first use in this function); did you mean ‘FUTEX_OP’?
  156 |   futex_flag = FUTEX_32 | (fshared * FUTEX_SHARED_FLAG);
      |                ^~~~~~~~
      |                FUTEX_OP
bench/futex-hash.c:156:16: note: each undeclared identifier is reported only once for each function it appears in
bench/futex-hash.c:156:38: error: ‘FUTEX_SHARED_FLAG’ undeclared (first use in this function); did you mean ‘FUTEX_PRIVATE_FLAG’?
  156 |   futex_flag = FUTEX_32 | (fshared * FUTEX_SHARED_FLAG);
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      FUTEX_PRIVATE_FLAG

This reverts commit 799e24f7b39e114107b36c4cc4ece4825a9fa6a0.